debug: true
oauth:
    endpoint: http://ec2.kurio.nexway.com/connect/import
    consumer:
        key: REPLACE_WITH_CONSUMER_KEY
        secret: REPLACE_WITH_CONSUMER_SECRET
    token:
        key: REPLACE_WITH_TOKEN_KEY
        secret: REPLACE_WITH_TOKEN_SECRET